import type { BusinessType } from "./types";

export const BUSINESS_TYPES: BusinessType[] = [
  {
    id: "supermarket",
    label: "Supermarket",
    icon: "shopping-basket",
    tagline: "Full aisles, fast checkout.",
    accent: "#2F6F4F",
    categories: ["Groceries", "Drinks", "Household", "Frozen"],
    products: [
      { id: "sm-1", name: "Rice 5kg", price: 8500, category: "Groceries", emoji: "🍚", stock: 24 },
      { id: "sm-2", name: "Cooking Oil 2L", price: 5200, category: "Groceries", emoji: "🫙", stock: 18 },
      { id: "sm-3", name: "Sugar 1kg", price: 1600, category: "Groceries", emoji: "🍬", stock: 40 },
      { id: "sm-4", name: "Maize Flour 2kg", price: 2400, category: "Groceries", emoji: "🌽", stock: 30 },
      { id: "sm-5", name: "Bread Loaf", price: 1200, category: "Groceries", emoji: "🍞", stock: 4 },
      { id: "sm-6", name: "Milk 1L", price: 1400, category: "Drinks", emoji: "🥛", stock: 22 },
      { id: "sm-7", name: "Coca Cola 1.5L", price: 1800, category: "Drinks", emoji: "🥤", stock: 3 },
      { id: "sm-8", name: "Bottled Water 1.5L", price: 900, category: "Drinks", emoji: "💧", stock: 60 },
      { id: "sm-9", name: "Dish Soap", price: 2200, category: "Household", emoji: "🧴", stock: 15 },
      { id: "sm-10", name: "Toilet Paper 12pk", price: 4800, category: "Household", emoji: "🧻", stock: 12 },
      { id: "sm-11", name: "Frozen Chicken 1kg", price: 4200, category: "Frozen", emoji: "🧊", stock: 9 },
      { id: "sm-12", name: "Tea Leaves 250g", price: 2100, category: "Groceries", emoji: "🍵", stock: 20 },
    ],
  },
  {
    id: "grocery",
    label: "Grocery Shop",
    icon: "apple",
    tagline: "Fresh from the corner shop.",
    accent: "#4C7A3D",
    categories: ["Fresh Produce", "Staples", "Drinks", "Snacks"],
    products: [
      { id: "gr-1", name: "Tomatoes (kg)", price: 900, category: "Fresh Produce", emoji: "🍅", stock: 25 },
      { id: "gr-2", name: "Onions (kg)", price: 800, category: "Fresh Produce", emoji: "🧅", stock: 30 },
      { id: "gr-3", name: "Bananas (bunch)", price: 1500, category: "Fresh Produce", emoji: "🍌", stock: 14 },
      { id: "gr-4", name: "Avocado", price: 400, category: "Fresh Produce", emoji: "🥑", stock: 2 },
      { id: "gr-5", name: "Bread Loaf", price: 1200, category: "Staples", emoji: "🍞", stock: 8 },
      { id: "gr-6", name: "Eggs (tray)", price: 3500, category: "Staples", emoji: "🥚", stock: 10 },
      { id: "gr-7", name: "Sugar 1kg", price: 1600, category: "Staples", emoji: "🍬", stock: 18 },
      { id: "gr-8", name: "Salt 500g", price: 400, category: "Staples", emoji: "🧂", stock: 40 },
      { id: "gr-9", name: "Cooking Oil 1L", price: 2500, category: "Staples", emoji: "🫙", stock: 16 },
      { id: "gr-10", name: "Soda 500ml", price: 700, category: "Drinks", emoji: "🥤", stock: 35 },
      { id: "gr-11", name: "Biscuits Pack", price: 900, category: "Snacks", emoji: "🍪", stock: 22 },
    ],
  },
  {
    id: "electronics",
    label: "Electronics Store",
    icon: "plug",
    tagline: "Power, plugged in.",
    accent: "#2563EB",
    categories: ["Phones", "Audio", "Computing", "Accessories"],
    products: [
      { id: "el-1", name: "Phone Charger", price: 8500, category: "Phones", emoji: "🔌", stock: 20 },
      { id: "el-2", name: "USB-C Cable", price: 3000, category: "Accessories", emoji: "🔋", stock: 30 },
      { id: "el-3", name: "Wireless Earbuds", price: 22000, category: "Audio", emoji: "🎧", stock: 6 },
      { id: "el-4", name: "Bluetooth Speaker", price: 35000, category: "Audio", emoji: "🔊", stock: 4 },
      { id: "el-5", name: "Power Bank 10000mAh", price: 18000, category: "Accessories", emoji: "🔋", stock: 11 },
      { id: "el-6", name: "HDMI Cable", price: 4500, category: "Computing", emoji: "📺", stock: 14 },
      { id: "el-7", name: "Wireless Mouse", price: 9000, category: "Computing", emoji: "🖱️", stock: 9 },
      { id: "el-8", name: "Laptop Sleeve", price: 12000, category: "Computing", emoji: "💻", stock: 7 },
      { id: "el-9", name: "Screen Protector", price: 2000, category: "Phones", emoji: "📱", stock: 1 },
      { id: "el-10", name: "Extension Cord", price: 6500, category: "Accessories", emoji: "🔗", stock: 13 },
    ],
  },
  {
    id: "clothing",
    label: "Clothing & Fashion",
    icon: "shirt",
    tagline: "Racks that turn heads.",
    accent: "#C2185B",
    categories: ["Men", "Women", "Kids", "Accessories"],
    products: [
      { id: "cl-1", name: "Men's T-Shirt", price: 6500, category: "Men", emoji: "👕", stock: 26 },
      { id: "cl-2", name: "Denim Jeans", price: 15000, category: "Men", emoji: "👖", stock: 12 },
      { id: "cl-3", name: "Women's Blouse", price: 11000, category: "Women", emoji: "👚", stock: 15 },
      { id: "cl-4", name: "Summer Dress", price: 18000, category: "Women", emoji: "👗", stock: 5 },
      { id: "cl-5", name: "Ankara Skirt", price: 14000, category: "Women", emoji: "🩱", stock: 8 },
      { id: "cl-6", name: "Kids Hoodie", price: 9500, category: "Kids", emoji: "🧥", stock: 10 },
      { id: "cl-7", name: "Leather Belt", price: 7000, category: "Accessories", emoji: "🪢", stock: 19 },
      { id: "cl-8", name: "Silk Scarf", price: 8000, category: "Accessories", emoji: "🧣", stock: 3 },
      { id: "cl-9", name: "Baseball Cap", price: 5000, category: "Accessories", emoji: "🧢", stock: 22 },
      { id: "cl-10", name: "Sunglasses", price: 9500, category: "Accessories", emoji: "🕶️", stock: 6 },
    ],
  },
  {
    id: "shoes",
    label: "Shoe Store",
    icon: "footprints",
    tagline: "Built to walk out the door.",
    accent: "#7C4A2D",
    categories: ["Sneakers", "Formal", "Sandals", "Kids"],
    products: [
      { id: "sh-1", name: "Running Sneakers", price: 32000, category: "Sneakers", emoji: "👟", stock: 9 },
      { id: "sh-2", name: "Canvas Sneakers", price: 21000, category: "Sneakers", emoji: "👟", stock: 14 },
      { id: "sh-3", name: "Leather Oxfords", price: 45000, category: "Formal", emoji: "👞", stock: 5 },
      { id: "sh-4", name: "Loafers", price: 38000, category: "Formal", emoji: "🥿", stock: 6 },
      { id: "sh-5", name: "Heeled Sandals", price: 26000, category: "Sandals", emoji: "👠", stock: 4 },
      { id: "sh-6", name: "Flip Flops", price: 4000, category: "Sandals", emoji: "🩴", stock: 30 },
      { id: "sh-7", name: "Hiking Boots", price: 42000, category: "Formal", emoji: "🥾", stock: 3 },
      { id: "sh-8", name: "Kids School Shoes", price: 15000, category: "Kids", emoji: "👞", stock: 11 },
      { id: "sh-9", name: "Ballet Flats", price: 19000, category: "Sandals", emoji: "🩰", stock: 8 },
      { id: "sh-10", name: "Sports Cleats", price: 27000, category: "Sneakers", emoji: "⚽", stock: 2 },
    ],
  },
  {
    id: "hardware",
    label: "Hardware Store",
    icon: "hammer",
    tagline: "Fix it, build it, wire it.",
    accent: "#D97706",
    categories: ["Tools", "Electrical", "Plumbing", "Paint"],
    products: [
      { id: "hw-1", name: "Claw Hammer", price: 6500, category: "Tools", emoji: "🔨", stock: 15 },
      { id: "hw-2", name: "Screwdriver Set", price: 8500, category: "Tools", emoji: "🪛", stock: 12 },
      { id: "hw-3", name: "Measuring Tape", price: 3500, category: "Tools", emoji: "📏", stock: 20 },
      { id: "hw-4", name: "Padlock", price: 4500, category: "Tools", emoji: "🔒", stock: 18 },
      { id: "hw-5", name: "LED Bulb 9W", price: 2200, category: "Electrical", emoji: "💡", stock: 40 },
      { id: "hw-6", name: "Extension Socket", price: 5500, category: "Electrical", emoji: "🔌", stock: 9 },
      { id: "hw-7", name: "PVC Pipe 1m", price: 3200, category: "Plumbing", emoji: "🚰", stock: 25 },
      { id: "hw-8", name: "Nails (1kg)", price: 2800, category: "Tools", emoji: "🔩", stock: 33 },
      { id: "hw-9", name: "Wall Paint 4L", price: 22000, category: "Paint", emoji: "🎨", stock: 4 },
      { id: "hw-10", name: "Paint Brush", price: 1800, category: "Paint", emoji: "🖌️", stock: 27 },
    ],
  },
  {
    id: "pharmacy",
    label: "Pharmacy",
    icon: "pill",
    tagline: "Health, dispensed with care.",
    accent: "#0D9488",
    categories: ["Medicine", "Wellness", "Baby Care", "First Aid"],
    products: [
      { id: "ph-1", name: "Paracetamol (pack)", price: 800, category: "Medicine", emoji: "💊", stock: 60 },
      { id: "ph-2", name: "Vitamin C Tablets", price: 3500, category: "Wellness", emoji: "🍊", stock: 20 },
      { id: "ph-3", name: "Cough Syrup", price: 4200, category: "Medicine", emoji: "🍯", stock: 10 },
      { id: "ph-4", name: "Hand Sanitizer 250ml", price: 2000, category: "Wellness", emoji: "🧴", stock: 35 },
      { id: "ph-5", name: "Face Masks (box)", price: 5000, category: "First Aid", emoji: "😷", stock: 18 },
      { id: "ph-6", name: "Bandage Roll", price: 1500, category: "First Aid", emoji: "🩹", stock: 25 },
      { id: "ph-7", name: "Antiseptic Cream", price: 2800, category: "First Aid", emoji: "🧴", stock: 3 },
      { id: "ph-8", name: "Baby Diapers (pack)", price: 9500, category: "Baby Care", emoji: "🍼", stock: 12 },
      { id: "ph-9", name: "Oral Rehydration Salts", price: 900, category: "Wellness", emoji: "🧂", stock: 40 },
      { id: "ph-10", name: "Blood Pressure Monitor", price: 38000, category: "Wellness", emoji: "🩺", stock: 2 },
    ],
  },
  {
    id: "bookstore",
    label: "Bookstore & Stationery",
    icon: "book-open",
    tagline: "Pages, pens and planners.",
    accent: "#4338CA",
    categories: ["Books", "Stationery", "Art Supplies", "Office"],
    products: [
      { id: "bk-1", name: "Notebook A4", price: 1200, category: "Stationery", emoji: "📓", stock: 40 },
      { id: "bk-2", name: "Ballpoint Pens (pack)", price: 1500, category: "Stationery", emoji: "🖊️", stock: 32 },
      { id: "bk-3", name: "Novel Paperback", price: 8500, category: "Books", emoji: "📖", stock: 15 },
      { id: "bk-4", name: "Sticky Notes", price: 1000, category: "Stationery", emoji: "🗒️", stock: 24 },
      { id: "bk-5", name: "Highlighter Set", price: 3200, category: "Art Supplies", emoji: "🖍️", stock: 18 },
      { id: "bk-6", name: "Printer Paper (ream)", price: 6000, category: "Office", emoji: "🖨️", stock: 9 },
      { id: "bk-7", name: "Geometry Set", price: 2500, category: "Stationery", emoji: "📐", stock: 14 },
      { id: "bk-8", name: "Whiteboard Marker", price: 1800, category: "Office", emoji: "🖊️", stock: 22 },
      { id: "bk-9", name: "Backpack", price: 21000, category: "Office", emoji: "🎒", stock: 6 },
      { id: "bk-10", name: "Calculator", price: 9000, category: "Office", emoji: "🧮", stock: 4 },
    ],
  },
  {
    id: "furniture",
    label: "Furniture Store",
    icon: "armchair",
    tagline: "Rooms, ready to live in.",
    accent: "#92400E",
    categories: ["Living Room", "Bedroom", "Office", "Decor"],
    products: [
      { id: "fn-1", name: "Wooden Dining Chair", price: 45000, category: "Living Room", emoji: "🪑", stock: 10 },
      { id: "fn-2", name: "3-Seater Sofa", price: 380000, category: "Living Room", emoji: "🛋️", stock: 2 },
      { id: "fn-3", name: "Coffee Table", price: 65000, category: "Living Room", emoji: "🪵", stock: 5 },
      { id: "fn-4", name: "Queen Bed Frame", price: 220000, category: "Bedroom", emoji: "🛏️", stock: 3 },
      { id: "fn-5", name: "Mattress (Queen)", price: 180000, category: "Bedroom", emoji: "🛌", stock: 4 },
      { id: "fn-6", name: "Bedside Lamp", price: 15000, category: "Bedroom", emoji: "🛋️", stock: 12 },
      { id: "fn-7", name: "Wardrobe", price: 260000, category: "Bedroom", emoji: "🚪", stock: 2 },
      { id: "fn-8", name: "Office Desk", price: 95000, category: "Office", emoji: "🗄️", stock: 6 },
      { id: "fn-9", name: "Bookshelf", price: 72000, category: "Office", emoji: "📚", stock: 5 },
      { id: "fn-10", name: "Wall Mirror", price: 28000, category: "Decor", emoji: "🪞", stock: 7 },
    ],
  },
  {
    id: "cosmetics",
    label: "Cosmetics & Beauty",
    icon: "sparkles",
    tagline: "Glow, bottled and boxed.",
    accent: "#DB2777",
    categories: ["Skincare", "Makeup", "Haircare", "Fragrance"],
    products: [
      { id: "co-1", name: "Facial Cleanser", price: 6500, category: "Skincare", emoji: "🧴", stock: 20 },
      { id: "co-2", name: "Sunscreen SPF50", price: 8500, category: "Skincare", emoji: "🧴", stock: 14 },
      { id: "co-3", name: "Shea Body Lotion", price: 5200, category: "Skincare", emoji: "🧴", stock: 25 },
      { id: "co-4", name: "Matte Lipstick", price: 4500, category: "Makeup", emoji: "💄", stock: 30 },
      { id: "co-5", name: "Foundation", price: 12000, category: "Makeup", emoji: "🧴", stock: 8 },
      { id: "co-6", name: "Eyeliner Pencil", price: 3200, category: "Makeup", emoji: "✏️", stock: 22 },
      { id: "co-7", name: "Makeup Brush Set", price: 15000, category: "Makeup", emoji: "🖌️", stock: 5 },
      { id: "co-8", name: "Hair Relaxer Kit", price: 9000, category: "Haircare", emoji: "💇", stock: 3 },
      { id: "co-9", name: "Nail Polish", price: 2500, category: "Makeup", emoji: "💅", stock: 40 },
      { id: "co-10", name: "Perfume 50ml", price: 22000, category: "Fragrance", emoji: "🌸", stock: 6 },
    ],
  },
  {
    id: "mobile",
    label: "Mobile Phones & Accessories",
    icon: "smartphone",
    tagline: "Every counter, connected.",
    accent: "#0EA5E9",
    categories: ["Smartphones", "Cases", "Chargers", "SIM & Airtime"],
    products: [
      { id: "mb-1", name: "Smartphone (Entry)", price: 95000, category: "Smartphones", emoji: "📱", stock: 6 },
      { id: "mb-2", name: "Smartphone (Mid-range)", price: 210000, category: "Smartphones", emoji: "📱", stock: 3 },
      { id: "mb-3", name: "Phone Case", price: 3500, category: "Cases", emoji: "📱", stock: 40 },
      { id: "mb-4", name: "Tempered Glass", price: 2000, category: "Cases", emoji: "🔲", stock: 50 },
      { id: "mb-5", name: "Fast Charger 25W", price: 9500, category: "Chargers", emoji: "🔌", stock: 18 },
      { id: "mb-6", name: "Power Bank", price: 17000, category: "Chargers", emoji: "🔋", stock: 9 },
      { id: "mb-7", name: "Bluetooth Earbuds", price: 19000, category: "Chargers", emoji: "🎧", stock: 7 },
      { id: "mb-8", name: "Airtime Voucher", price: 1000, category: "SIM & Airtime", emoji: "📶", stock: 100 },
      { id: "mb-9", name: "Car Phone Holder", price: 6000, category: "Cases", emoji: "🚗", stock: 11 },
      { id: "mb-10", name: "Selfie Stick", price: 5500, category: "Cases", emoji: "🤳", stock: 4 },
    ],
  },
  {
    id: "pet",
    label: "Pet Supply Store",
    icon: "paw-print",
    tagline: "For the whole household.",
    accent: "#16A34A",
    categories: ["Food", "Grooming", "Accessories", "Health"],
    products: [
      { id: "pt-1", name: "Dog Food 5kg", price: 22000, category: "Food", emoji: "🐶", stock: 10 },
      { id: "pt-2", name: "Cat Food 3kg", price: 15000, category: "Food", emoji: "🐱", stock: 12 },
      { id: "pt-3", name: "Bird Seed 1kg", price: 4500, category: "Food", emoji: "🐦", stock: 20 },
      { id: "pt-4", name: "Aquarium Fish Food", price: 2800, category: "Food", emoji: "🐟", stock: 25 },
      { id: "pt-5", name: "Pet Shampoo", price: 6500, category: "Grooming", emoji: "🧴", stock: 9 },
      { id: "pt-6", name: "Cat Litter 5kg", price: 8500, category: "Grooming", emoji: "🐾", stock: 14 },
      { id: "pt-7", name: "Chew Toy", price: 3500, category: "Accessories", emoji: "🦴", stock: 30 },
      { id: "pt-8", name: "Leash & Collar Set", price: 7500, category: "Accessories", emoji: "🐕", stock: 8 },
      { id: "pt-9", name: "Pet Carrier", price: 21000, category: "Accessories", emoji: "🧳", stock: 3 },
      { id: "pt-10", name: "Flea Treatment", price: 9500, category: "Health", emoji: "💊", stock: 2 },
    ],
  },
  {
    id: "bakery",
    label: "Bakery",
    icon: "croissant",
    tagline: "Warm from the oven.",
    accent: "#B45309",
    categories: ["Bread", "Pastries", "Cakes", "Drinks"],
    products: [
      { id: "bh-1", name: "White Bread Loaf", price: 1200, category: "Bread", emoji: "🍞", stock: 20 },
      { id: "bh-2", name: "Croissant", price: 1500, category: "Pastries", emoji: "🥐", stock: 15 },
      { id: "bh-3", name: "Doughnut", price: 1000, category: "Pastries", emoji: "🍩", stock: 24 },
      { id: "bh-4", name: "Chocolate Cupcake", price: 1800, category: "Pastries", emoji: "🧁", stock: 18 },
      { id: "bh-5", name: "Cinnamon Roll", price: 2000, category: "Pastries", emoji: "🥯", stock: 10 },
      { id: "bh-6", name: "Banana Muffin", price: 1600, category: "Pastries", emoji: "🧁", stock: 12 },
      { id: "bh-7", name: "Fruit Tart", price: 3200, category: "Pastries", emoji: "🥧", stock: 6 },
      { id: "bh-8", name: "Birthday Cake (1kg)", price: 18000, category: "Cakes", emoji: "🎂", stock: 3 },
      { id: "bh-9", name: "Meat Samosa", price: 800, category: "Pastries", emoji: "🥟", stock: 30 },
      { id: "bh-10", name: "Iced Coffee", price: 2500, category: "Drinks", emoji: "🧋", stock: 16 },
    ],
  },
  {
    id: "liquor",
    label: "Liquor Store",
    icon: "wine",
    tagline: "The bottle shop next door.",
    accent: "#7C2D12",
    categories: ["Beer", "Wine", "Spirits", "Soft Drinks"],
    products: [
      { id: "lq-1", name: "Lager Beer 500ml", price: 1500, category: "Beer", emoji: "🍺", stock: 60 },
      { id: "lq-2", name: "Cider 500ml", price: 1800, category: "Beer", emoji: "🍻", stock: 24 },
      { id: "lq-3", name: "Red Wine Bottle", price: 15000, category: "Wine", emoji: "🍷", stock: 10 },
      { id: "lq-4", name: "Sparkling Wine", price: 22000, category: "Wine", emoji: "🍾", stock: 4 },
      { id: "lq-5", name: "Whisky 750ml", price: 35000, category: "Spirits", emoji: "🥃", stock: 6 },
      { id: "lq-6", name: "Vodka 750ml", price: 28000, category: "Spirits", emoji: "🍸", stock: 8 },
      { id: "lq-7", name: "Gin 750ml", price: 30000, category: "Spirits", emoji: "🍸", stock: 3 },
      { id: "lq-8", name: "Mixer Tonic Water", price: 1200, category: "Soft Drinks", emoji: "🥤", stock: 35 },
      { id: "lq-9", name: "Energy Drink", price: 1600, category: "Soft Drinks", emoji: "🧃", stock: 28 },
      { id: "lq-10", name: "Ice Bag 2kg", price: 2000, category: "Soft Drinks", emoji: "🧊", stock: 15 },
    ],
  },
  {
    id: "chicken",
    label: "Chicken Store",
    icon: "drumstick",
    tagline: "Fresh cuts, fast counter.",
    accent: "#DC2626",
    categories: ["Whole Chicken", "Cuts", "Fried & Ready", "Sides & Drinks"],
    products: [
      { id: "ck-1", name: "Whole Chicken 1.5kg", price: 8500, category: "Whole Chicken", emoji: "🐔", stock: 12 },
      { id: "ck-2", name: "Chicken Breast (kg)", price: 6200, category: "Cuts", emoji: "🍗", stock: 20 },
      { id: "ck-3", name: "Chicken Thighs (kg)", price: 5400, category: "Cuts", emoji: "🍗", stock: 18 },
      { id: "ck-4", name: "Chicken Wings (kg)", price: 5800, category: "Cuts", emoji: "🍗", stock: 9 },
      { id: "ck-5", name: "2pc Fried Chicken Meal", price: 3500, category: "Fried & Ready", emoji: "🍗", stock: 25 },
      { id: "ck-6", name: "4pc Fried Chicken Bucket", price: 6500, category: "Fried & Ready", emoji: "🪣", stock: 14 },
      { id: "ck-7", name: "Chicken Nuggets (10pc)", price: 3000, category: "Fried & Ready", emoji: "🍗", stock: 22 },
      { id: "ck-8", name: "Chips Portion", price: 1500, category: "Sides & Drinks", emoji: "🍟", stock: 40 },
      { id: "ck-9", name: "Coleslaw Side", price: 1000, category: "Sides & Drinks", emoji: "🥗", stock: 16 },
      { id: "ck-10", name: "Soft Drink 500ml", price: 800, category: "Sides & Drinks", emoji: "🥤", stock: 50 },
    ],
  },
];
