from app.modules.sales.service.customer import (
    count_customers,
    create_customer,
    delete_customer,
    get_customer,
    list_customers,
    update_customer,
)
from app.modules.sales.service.deal import (
    count_deals,
    create_deal,
    delete_deal,
    get_deal,
    list_deals,
    update_deal,
)
from app.modules.sales.service.order import (
    count_orders,
    create_order,
    delete_order,
    get_order,
    list_orders,
    update_order,
)
from app.modules.sales.service.return_ import (
    count_returns,
    create_return,
    delete_return,
    get_return,
    list_returns,
    update_return,
)
from app.modules.sales.service.target import (
    count_targets,
    create_target,
    delete_target,
    get_target,
    list_targets,
    update_target,
)

__all__ = [
    "count_customers",
    "count_deals",
    "count_orders",
    "count_returns",
    "count_targets",
    "create_customer",
    "create_deal",
    "create_order",
    "create_return",
    "create_target",
    "delete_customer",
    "delete_deal",
    "delete_order",
    "delete_return",
    "delete_target",
    "get_customer",
    "get_deal",
    "get_order",
    "get_return",
    "get_target",
    "list_customers",
    "list_deals",
    "list_orders",
    "list_returns",
    "list_targets",
    "update_customer",
    "update_deal",
    "update_order",
    "update_return",
    "update_target",
]
