from app.modules.inventory.schemas.batch import BatchCreate, BatchRead, BatchUpdate
from app.modules.inventory.schemas.brand import BrandCreate, BrandRead, BrandUpdate
from app.modules.inventory.schemas.category import (
    CategoryCreate,
    CategoryImportRequest,
    CategoryImportResult,
    CategoryRead,
    CategoryTemplateGroup,
    CategoryTemplateRead,
    CategoryTemplatesRead,
    CategoryUpdate,
)
from app.modules.inventory.schemas.markdown import (
    GenerateVariantsRequest,
    GenerateVariantsResult,
    MarkdownLine,
    MarkdownReport,
    SizeSelloutLine,
    SizeSelloutReport,
)
from app.modules.inventory.schemas.product import (
    ProductBulkCreate,
    ProductBulkLine,
    ProductBulkResult,
    ProductCreate,
    ProductRead,
    ProductUpdate,
    RestockRequest,
    VariantCreate,
    VariantListRead,
    VariantRead,
    VariantUpdate,
)
from app.modules.inventory.schemas.serial import (
    SerialBulkCreate,
    SerialCreateItem,
    SerialRead,
    SerialUpdate,
    WarrantyClaimCreate,
    WarrantyClaimRead,
    WarrantyClaimUpdate,
)
from app.modules.inventory.schemas.stock import LowStockLine, LowStockReport
from app.modules.inventory.schemas.supplier import (
    SupplierBulkCreate,
    SupplierBulkResult,
    SupplierCreate,
    SupplierRead,
    SupplierUpdate,
)
from app.modules.inventory.schemas.transfer import (
    StockTransferCreate,
    StockTransferRead,
    StockTransferUpdate,
    TransferItemCreate,
    TransferItemRead,
)
from app.modules.inventory.schemas.unit import (
    UnitCreate,
    UnitImportRequest,
    UnitImportResult,
    UnitRead,
    UnitSuggestion,
    UnitSuggestionsRead,
    UnitUpdate,
)
from app.modules.inventory.schemas.valuation import (
    CategoryValuation,
    InventoryValuationReport,
    ValuationLine,
    ValuationSummary,
)

__all__ = [
    "BatchCreate",
    "BatchRead",
    "BatchUpdate",
    "BrandCreate",
    "BrandRead",
    "BrandUpdate",
    "CategoryCreate",
    "CategoryImportRequest",
    "CategoryImportResult",
    "CategoryRead",
    "CategoryTemplateGroup",
    "CategoryTemplateRead",
    "CategoryTemplatesRead",
    "CategoryUpdate",
    "CategoryValuation",
    "GenerateVariantsRequest",
    "GenerateVariantsResult",
    "InventoryValuationReport",
    "LowStockLine",
    "LowStockReport",
    "MarkdownLine",
    "MarkdownReport",
    "ProductBulkCreate",
    "ProductBulkLine",
    "ProductBulkResult",
    "ProductCreate",
    "ProductRead",
    "ProductUpdate",
    "RestockRequest",
    "SerialBulkCreate",
    "SerialCreateItem",
    "SerialRead",
    "SerialUpdate",
    "SizeSelloutLine",
    "SizeSelloutReport",
    "StockTransferCreate",
    "StockTransferRead",
    "StockTransferUpdate",
    "SupplierBulkCreate",
    "SupplierBulkResult",
    "SupplierCreate",
    "SupplierRead",
    "SupplierUpdate",
    "TransferItemCreate",
    "TransferItemRead",
    "UnitCreate",
    "UnitImportRequest",
    "UnitImportResult",
    "UnitRead",
    "UnitSuggestion",
    "UnitSuggestionsRead",
    "UnitUpdate",
    "ValuationLine",
    "ValuationSummary",
    "VariantCreate",
    "VariantListRead",
    "VariantRead",
    "VariantUpdate",
    "WarrantyClaimCreate",
    "WarrantyClaimRead",
    "WarrantyClaimUpdate",
]
