"""add product variants

Revision ID: 0e52800cbbcc
Revises: c5fd95430ed3
Create Date: 2026-08-01 12:41:14.185356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0e52800cbbcc'
down_revision: Union[str, None] = 'c5fd95430ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_variants_product_id', 'inventory_product_variants', ['product_id'], unique=False)
    op.create_index('uq_inventory_variants_product_sku', 'inventory_product_variants', ['product_id', 'sku'], unique=True, postgresql_where='sku IS NOT NULL')
    op.add_column('inventory_products', sa.Column('has_variants', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_products', 'has_variants')
    op.drop_index('uq_inventory_variants_product_sku', table_name='inventory_product_variants', postgresql_where='sku IS NOT NULL')
    op.drop_index('ix_inventory_variants_product_id', table_name='inventory_product_variants')
    op.drop_table('inventory_product_variants')
    # ### end Alembic commands ###
