"""add_crm_and_manufacturing_modules

Revision ID: 0e726f82fc3e
Revises: f7a9c1b2d3e4
Create Date: 2026-08-08 21:03:35.679218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e726f82fc3e'
down_revision: Union[str, None] = 'f7a9c1b2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_campaigns_tenant_id'), 'crm_campaigns', ['tenant_id'], unique=False)
    op.create_index('ix_crm_campaigns_tenant_status', 'crm_campaigns', ['tenant_id', 'status'], unique=False)
    op.create_table('crm_email_logs',
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crm_email_logs_campaign_id', 'crm_email_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_crm_email_logs_tenant_id'), 'crm_email_logs', ['tenant_id'], unique=False)
    op.create_index('ix_crm_email_logs_tenant_status', 'crm_email_logs', ['tenant_id', 'status'], unique=False)
    op.create_table('manufacturing_production_orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'order_number', name='uq_manufacturing_orders_tenant_number')
    )
    op.create_index('ix_manufacturing_orders_tenant_status', 'manufacturing_production_orders', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_manufacturing_production_orders_tenant_id'), 'manufacturing_production_orders', ['tenant_id'], unique=False)
    op.create_table('manufacturing_production_items',
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_order_id'], ['manufacturing_production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manufacturing_items_order_id', 'manufacturing_production_items', ['production_order_id'], unique=False)
    op.create_index('ix_manufacturing_items_product_id', 'manufacturing_production_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manufacturing_items_product_id', table_name='manufacturing_production_items')
    op.drop_index('ix_manufacturing_items_order_id', table_name='manufacturing_production_items')
    op.drop_table('manufacturing_production_items')
    op.drop_index(op.f('ix_manufacturing_production_orders_tenant_id'), table_name='manufacturing_production_orders')
    op.drop_index('ix_manufacturing_orders_tenant_status', table_name='manufacturing_production_orders')
    op.drop_table('manufacturing_production_orders')
    op.drop_index('ix_crm_email_logs_tenant_status', table_name='crm_email_logs')
    op.drop_index(op.f('ix_crm_email_logs_tenant_id'), table_name='crm_email_logs')
    op.drop_index('ix_crm_email_logs_campaign_id', table_name='crm_email_logs')
    op.drop_table('crm_email_logs')
    op.drop_index('ix_crm_campaigns_tenant_status', table_name='crm_campaigns')
    op.drop_index(op.f('ix_crm_campaigns_tenant_id'), table_name='crm_campaigns')
    op.drop_table('crm_campaigns')
    # ### end Alembic commands ###
