"""add stock transfers and markdown pricing

Revision ID: 20d8cc2353bb
Revises: 61db154e34c9
Create Date: 2026-08-11 17:35:04.362130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20d8cc2353bb'
down_revision: Union[str, None] = '61db154e34c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_stock_transfers',
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('from_branch_id', sa.UUID(), nullable=True),
    sa.Column('to_branch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_stock_transfers_tenant_id'), 'inventory_stock_transfers', ['tenant_id'], unique=False)
    op.create_index('ix_inventory_transfers_tenant_status', 'inventory_stock_transfers', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_inventory_transfers_tenant_number', 'inventory_stock_transfers', ['tenant_id', 'transfer_number'], unique=True)
    op.create_table('inventory_stock_transfer_items',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('variant_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory_stock_transfers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['inventory_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_transfer_items_transfer_id', 'inventory_stock_transfer_items', ['transfer_id'], unique=False)
    op.add_column('inventory_product_variants', sa.Column('promo_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('inventory_product_variants', sa.Column('promo_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_products', sa.Column('promo_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('inventory_products', sa.Column('promo_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_products', 'promo_ends_at')
    op.drop_column('inventory_products', 'promo_price')
    op.drop_column('inventory_product_variants', 'promo_ends_at')
    op.drop_column('inventory_product_variants', 'promo_price')
    op.drop_index('ix_inventory_transfer_items_transfer_id', table_name='inventory_stock_transfer_items')
    op.drop_table('inventory_stock_transfer_items')
    op.drop_index('uq_inventory_transfers_tenant_number', table_name='inventory_stock_transfers')
    op.drop_index('ix_inventory_transfers_tenant_status', table_name='inventory_stock_transfers')
    op.drop_index(op.f('ix_inventory_stock_transfers_tenant_id'), table_name='inventory_stock_transfers')
    op.drop_table('inventory_stock_transfers')
    # ### end Alembic commands ###
