"""add services catalog and staff-service assignments

Revision ID: 53acafcbe39c
Revises: eae76a75f47d
Create Date: 2026-09-29 19:12:44.481453

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '53acafcbe39c'
down_revision: str | None = 'eae76a75f47d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_tenant_id'), 'service_categories', ['tenant_id'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_tenant_active', 'services', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_services_tenant_category', 'services', ['tenant_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('employee_services',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('commission_type', sa.String(length=20), nullable=True),
    sa.Column('commission_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_override_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'service_id', name='uq_employee_services_employee_service')
    )
    op.create_index('ix_employee_services_employee_id', 'employee_services', ['employee_id'], unique=False)
    op.create_index('ix_employee_services_service_id', 'employee_services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_services_service_id', table_name='employee_services')
    op.drop_index('ix_employee_services_employee_id', table_name='employee_services')
    op.drop_table('employee_services')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_index('ix_services_tenant_category', table_name='services')
    op.drop_index('ix_services_tenant_active', table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_service_categories_tenant_id'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
