"""add serials, warranty, barcode, unit conversion, decimal qty

Revision ID: 61db154e34c9
Revises: 497c60859524
Create Date: 2026-08-11 17:29:24.411246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61db154e34c9'
down_revision: Union[str, None] = '497c60859524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_product_serials',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('warranty_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['inventory_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_product_serials_tenant_id'), 'inventory_product_serials', ['tenant_id'], unique=False)
    op.create_index('ix_inventory_serials_tenant_product', 'inventory_product_serials', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_inventory_serials_tenant_status', 'inventory_product_serials', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_inventory_serials_tenant_serial', 'inventory_product_serials', ['tenant_id', 'serial_number'], unique=True)
    op.create_table('inventory_warranty_claims',
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('serial_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serial_id'], ['inventory_product_serials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_warranty_claims_tenant_id'), 'inventory_warranty_claims', ['tenant_id'], unique=False)
    op.create_index('ix_inventory_warranty_tenant_serial', 'inventory_warranty_claims', ['tenant_id', 'serial_id'], unique=False)
    op.create_index('ix_inventory_warranty_tenant_status', 'inventory_warranty_claims', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_inventory_warranty_tenant_number', 'inventory_warranty_claims', ['tenant_id', 'claim_number'], unique=True)
    op.add_column('inventory_product_variants', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.alter_column('inventory_product_variants', 'stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_product_variants', 'min_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
    op.add_column('inventory_products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('inventory_products', sa.Column('tracks_serials', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('inventory_products', sa.Column('sale_by_weight', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('inventory_products', sa.Column('conversion_factor', sa.Numeric(precision=14, scale=3), server_default=sa.text('1'), nullable=False))
    op.add_column('inventory_products', sa.Column('sale_unit_id', sa.UUID(), nullable=True))
    op.add_column('inventory_products', sa.Column('purchase_unit_id', sa.UUID(), nullable=True))
    op.alter_column('inventory_products', 'stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_products', 'min_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
    op.create_foreign_key(None, 'inventory_products', 'inventory_units', ['purchase_unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_products', 'inventory_units', ['sale_unit_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sales_order_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_order_items', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'inventory_products', type_='foreignkey')
    op.drop_constraint(None, 'inventory_products', type_='foreignkey')
    op.alter_column('inventory_products', 'min_stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('inventory_products', 'stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('inventory_products', 'purchase_unit_id')
    op.drop_column('inventory_products', 'sale_unit_id')
    op.drop_column('inventory_products', 'conversion_factor')
    op.drop_column('inventory_products', 'sale_by_weight')
    op.drop_column('inventory_products', 'tracks_serials')
    op.drop_column('inventory_products', 'barcode')
    op.alter_column('inventory_product_variants', 'min_stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('inventory_product_variants', 'stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('inventory_product_variants', 'barcode')
    op.drop_index('uq_inventory_warranty_tenant_number', table_name='inventory_warranty_claims')
    op.drop_index('ix_inventory_warranty_tenant_status', table_name='inventory_warranty_claims')
    op.drop_index('ix_inventory_warranty_tenant_serial', table_name='inventory_warranty_claims')
    op.drop_index(op.f('ix_inventory_warranty_claims_tenant_id'), table_name='inventory_warranty_claims')
    op.drop_table('inventory_warranty_claims')
    op.drop_index('uq_inventory_serials_tenant_serial', table_name='inventory_product_serials')
    op.drop_index('ix_inventory_serials_tenant_status', table_name='inventory_product_serials')
    op.drop_index('ix_inventory_serials_tenant_product', table_name='inventory_product_serials')
    op.drop_index(op.f('ix_inventory_product_serials_tenant_id'), table_name='inventory_product_serials')
    op.drop_table('inventory_product_serials')
    # ### end Alembic commands ###
