"""decimal purchase quantity

Revision ID: 80f8e2ce4e3c
Revises: 20d8cc2353bb
Create Date: 2026-08-11 17:44:01.144360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80f8e2ce4e3c'
down_revision: Union[str, None] = '20d8cc2353bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_items', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
