"""add hr module

Revision ID: b6f2a9c1e7d4
Revises: a3f1c2b9d4e5
Create Date: 2026-08-02 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6f2a9c1e7d4'
down_revision: Union[str, None] = 'a3f1c2b9d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_employees',
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_employees_department_id', 'hr_employees', ['department_id'], unique=False)
    op.create_index('ix_hr_employees_tenant_id', 'hr_employees', ['tenant_id'], unique=False)
    op.create_index('uq_hr_employees_tenant_code', 'hr_employees', ['tenant_id', 'employee_code'], unique=True)
    op.create_table('hr_attendance',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.String(length=5), nullable=True),
    sa.Column('check_out', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_attendance_date', 'hr_attendance', ['date'], unique=False)
    op.create_index('ix_hr_attendance_tenant_id', 'hr_attendance', ['tenant_id'], unique=False)
    op.create_index('uq_hr_attendance_tenant_employee_date', 'hr_attendance', ['tenant_id', 'employee_id', 'date'], unique=True)
    op.create_table('hr_leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=30), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_leave_requests_status', 'hr_leave_requests', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_hr_leave_requests_tenant_id', 'hr_leave_requests', ['tenant_id'], unique=False)
    op.create_table('hr_payroll_entries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_payroll_period', 'hr_payroll_entries', ['period'], unique=False)
    op.create_index('ix_hr_payroll_tenant_id', 'hr_payroll_entries', ['tenant_id'], unique=False)
    op.create_index('uq_hr_payroll_tenant_employee_period', 'hr_payroll_entries', ['tenant_id', 'employee_id', 'period'], unique=True)
    op.create_table('hr_applicants',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_applicants_stage', 'hr_applicants', ['tenant_id', 'stage'], unique=False)
    op.create_index('ix_hr_applicants_tenant_id', 'hr_applicants', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hr_applicants_tenant_id', table_name='hr_applicants')
    op.drop_index('ix_hr_applicants_stage', table_name='hr_applicants')
    op.drop_table('hr_applicants')
    op.drop_index('uq_hr_payroll_tenant_employee_period', table_name='hr_payroll_entries')
    op.drop_index('ix_hr_payroll_tenant_id', table_name='hr_payroll_entries')
    op.drop_index('ix_hr_payroll_period', table_name='hr_payroll_entries')
    op.drop_table('hr_payroll_entries')
    op.drop_index('ix_hr_leave_requests_tenant_id', table_name='hr_leave_requests')
    op.drop_index('ix_hr_leave_requests_status', table_name='hr_leave_requests')
    op.drop_table('hr_leave_requests')
    op.drop_index('uq_hr_attendance_tenant_employee_date', table_name='hr_attendance')
    op.drop_index('ix_hr_attendance_tenant_id', table_name='hr_attendance')
    op.drop_index('ix_hr_attendance_date', table_name='hr_attendance')
    op.drop_table('hr_attendance')
    op.drop_index('uq_hr_employees_tenant_code', table_name='hr_employees')
    op.drop_index('ix_hr_employees_tenant_id', table_name='hr_employees')
    op.drop_index('ix_hr_employees_department_id', table_name='hr_employees')
    op.drop_table('hr_employees')
    # ### end Alembic commands ###
