"""add finance tax tables

Revision ID: c2d3e4f5a6b7
Revises: b6f2a9c1e7d4
Create Date: 2026-08-02 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2d3e4f5a6b7'
down_revision: Union[str, None] = 'b6f2a9c1e7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_tax_configs',
    sa.Column('tax_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('min_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_threshold', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_tax_configs_tax_type', 'finance_tax_configs', ['tax_type'], unique=False)
    op.create_index('ix_finance_tax_configs_tenant_id', 'finance_tax_configs', ['tenant_id'], unique=False)
    op.create_index('uq_finance_tax_configs_tenant_type', 'finance_tax_configs', ['tenant_id', 'tax_type'], unique=True)
    op.create_table('finance_tax_calculations',
    sa.Column('calculation_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_tax_calculations_type_status', 'finance_tax_calculations', ['calculation_type', 'status'], unique=False)
    op.create_index('ix_finance_tax_calculations_period', 'finance_tax_calculations', ['period'], unique=False)
    op.create_index('ix_finance_tax_calculations_tenant_id', 'finance_tax_calculations', ['tenant_id'], unique=False)
    op.create_table('finance_tax_payments',
    sa.Column('payment_reference', sa.String(length=50), nullable=False),
    sa.Column('tax_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_tax_payments_period', 'finance_tax_payments', ['period'], unique=False)
    op.create_index('ix_finance_tax_payments_tenant_id', 'finance_tax_payments', ['tenant_id'], unique=False)
    op.create_index('uq_finance_tax_payments_tenant_ref', 'finance_tax_payments', ['tenant_id', 'payment_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_finance_tax_payments_tenant_ref', table_name='finance_tax_payments')
    op.drop_index('ix_finance_tax_payments_tenant_id', table_name='finance_tax_payments')
    op.drop_index('ix_finance_tax_payments_period', table_name='finance_tax_payments')
    op.drop_table('finance_tax_payments')
    op.drop_index('ix_finance_tax_calculations_tenant_id', table_name='finance_tax_calculations')
    op.drop_index('ix_finance_tax_calculations_period', table_name='finance_tax_calculations')
    op.drop_index('ix_finance_tax_calculations_type_status', table_name='finance_tax_calculations')
    op.drop_table('finance_tax_calculations')
    op.drop_index('uq_finance_tax_configs_tenant_type', table_name='finance_tax_configs')
    op.drop_index('ix_finance_tax_configs_tenant_id', table_name='finance_tax_configs')
    op.drop_index('ix_finance_tax_configs_tax_type', table_name='finance_tax_configs')
    op.drop_table('finance_tax_configs')
    # ### end Alembic commands ###
