"""add credit sales, customer debt and partial payments

Revision ID: c37169a80ee5
Revises: 4152e08f713b
Create Date: 2026-09-30 00:14:18.396623

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c37169a80ee5'
down_revision: str | None = 'e6c78e180752'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_order_payments',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_payment_id', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('accounting_transaction_id', sa.UUID(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accounting_transaction_id'], ['accounting_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_order_payments_customer_id', 'sales_order_payments', ['customer_id'], unique=False)
    op.create_index('ix_sales_order_payments_order_id', 'sales_order_payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_sales_order_payments_tenant_id'), 'sales_order_payments', ['tenant_id'], unique=False)
    op.create_index('uq_sales_order_payments_tenant_client', 'sales_order_payments', ['tenant_id', 'client_payment_id'], unique=True, postgresql_where='client_payment_id IS NOT NULL')
    op.create_index('uq_sales_order_payments_tenant_ref', 'sales_order_payments', ['tenant_id', 'reference'], unique=True)
    # Server default lets this NOT NULL column land on a table that already
    # has rows; the backfill below then gives every historical Completed
    # order its true amount_paid (== total, matching the "every completed
    # sale was fully paid" assumption the system made before this feature
    # existed) instead of leaving them all looking like fresh Unpaid debt.
    op.add_column('sales_orders', sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('sales_orders', sa.Column('due_date', sa.Date(), nullable=True))
    op.execute("UPDATE sales_orders SET amount_paid = total WHERE status = 'Completed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'due_date')
    op.drop_column('sales_orders', 'amount_paid')
    op.drop_index('uq_sales_order_payments_tenant_ref', table_name='sales_order_payments')
    op.drop_index('uq_sales_order_payments_tenant_client', table_name='sales_order_payments', postgresql_where='client_payment_id IS NOT NULL')
    op.drop_index(op.f('ix_sales_order_payments_tenant_id'), table_name='sales_order_payments')
    op.drop_index('ix_sales_order_payments_order_id', table_name='sales_order_payments')
    op.drop_index('ix_sales_order_payments_customer_id', table_name='sales_order_payments')
    op.drop_table('sales_order_payments')
    # ### end Alembic commands ###
