"""add finance module

Revision ID: c5fd95430ed3
Revises: a1b2c3d4e5f6
Create Date: 2026-08-01 12:31:44.735493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c5fd95430ed3'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_accounts',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('normal_balance', sa.String(length=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_accounts_tenant_id', 'finance_accounts', ['tenant_id'], unique=False)
    op.create_index('ix_finance_accounts_type', 'finance_accounts', ['tenant_id', 'type'], unique=False)
    op.create_index('uq_finance_accounts_tenant_code', 'finance_accounts', ['tenant_id', 'code'], unique=True)
    op.create_table('finance_budgets',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_budgets_account_id', 'finance_budgets', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_budgets_tenant_id'), 'finance_budgets', ['tenant_id'], unique=False)
    op.create_index('uq_finance_budgets_tenant_account_period', 'finance_budgets', ['tenant_id', 'account_id', 'period'], unique=True)
    op.create_table('finance_expenses',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_expenses_account_id', 'finance_expenses', ['account_id'], unique=False)
    op.create_index('ix_finance_expenses_tenant_id', 'finance_expenses', ['tenant_id'], unique=False)
    op.create_index('ix_finance_expenses_tenant_status', 'finance_expenses', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_finance_expenses_tenant_ref', 'finance_expenses', ['tenant_id', 'reference'], unique=True)
    op.create_table('finance_transactions',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('return_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_transactions_order_id', 'finance_transactions', ['order_id'], unique=False)
    op.create_index('ix_finance_transactions_tenant_id', 'finance_transactions', ['tenant_id'], unique=False)
    op.create_index('ix_finance_transactions_type_status', 'finance_transactions', ['tenant_id', 'type', 'status'], unique=False)
    op.create_index('uq_finance_transactions_tenant_ref', 'finance_transactions', ['tenant_id', 'reference'], unique=True)
    op.create_table('finance_transaction_lines',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_txn_lines_account_id', 'finance_transaction_lines', ['account_id'], unique=False)
    op.create_index('ix_finance_txn_lines_transaction_id', 'finance_transaction_lines', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finance_txn_lines_transaction_id', table_name='finance_transaction_lines')
    op.drop_index('ix_finance_txn_lines_account_id', table_name='finance_transaction_lines')
    op.drop_table('finance_transaction_lines')
    op.drop_index('uq_finance_transactions_tenant_ref', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_type_status', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_tenant_id', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_order_id', table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index('uq_finance_expenses_tenant_ref', table_name='finance_expenses')
    op.drop_index('ix_finance_expenses_tenant_status', table_name='finance_expenses')
    op.drop_index('ix_finance_expenses_tenant_id', table_name='finance_expenses')
    op.drop_index('ix_finance_expenses_account_id', table_name='finance_expenses')
    op.drop_table('finance_expenses')
    op.drop_index('uq_finance_budgets_tenant_account_period', table_name='finance_budgets')
    op.drop_index(op.f('ix_finance_budgets_tenant_id'), table_name='finance_budgets')
    op.drop_index('ix_finance_budgets_account_id', table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index('uq_finance_accounts_tenant_code', table_name='finance_accounts')
    op.drop_index('ix_finance_accounts_type', table_name='finance_accounts')
    op.drop_index('ix_finance_accounts_tenant_id', table_name='finance_accounts')
    op.drop_table('finance_accounts')
    # ### end Alembic commands ###
