"""add_image_url_to_products

Revision ID: d4d95d7e39c7
Revises: 7e5a5a2a6cbb
Create Date: 2026-07-31 16:56:48.743720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4d95d7e39c7'
down_revision: Union[str, None] = '7e5a5a2a6cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_products', 'image_url')
    # ### end Alembic commands ###
