"""add procurement module

Revision ID: f7a9c1b2d3e4
Revises: c2d3e4f5a6b7
Create Date: 2026-08-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7a9c1b2d3e4'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['inventory_suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('ix_purchase_orders_tenant_id', 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index('ix_purchase_orders_tenant_status', 'purchase_orders', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_purchase_orders_tenant_ref', 'purchase_orders', ['tenant_id', 'reference'], unique=True)
    op.create_table('purchase_items',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('variant_attributes', sa.JSON(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['inventory_product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_items_product_id', 'purchase_items', ['product_id'], unique=False)
    op.create_index('ix_purchase_items_purchase_order_id', 'purchase_items', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_items_variant_id', 'purchase_items', ['variant_id'], unique=False)
    op.add_column('finance_transactions', sa.Column('purchase_id', sa.UUID(), nullable=True))
    op.create_index('ix_finance_transactions_purchase_id', 'finance_transactions', ['purchase_id'], unique=False)
    op.create_foreign_key(None, 'finance_transactions', 'purchase_orders', ['purchase_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_index('ix_finance_transactions_purchase_id', table_name='finance_transactions')
    op.drop_column('finance_transactions', 'purchase_id')
    op.drop_index('ix_purchase_items_variant_id', table_name='purchase_items')
    op.drop_index('ix_purchase_items_purchase_order_id', table_name='purchase_items')
    op.drop_index('ix_purchase_items_product_id', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('uq_purchase_orders_tenant_ref', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_tenant_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_tenant_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
