import csv
import io
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

# Strict allowlist — a row dict can only ever expose what's listed here, so a
# bug elsewhere building the row (e.g. accidentally including hashed_password)
# can never leak into an export: unknown keys are simply never read.
COLUMN_DEFS: dict[str, tuple[str, Callable[[dict], str]]] = {
    "full_name": ("Full Name", lambda u: u["full_name"] or ""),
    "email": ("Email", lambda u: u["email"] or ""),
    "phone": ("Phone", lambda u: u["phone"] or ""),
    "tenant_name": ("Business", lambda u: u["tenant_name"] or "—"),
    "role": ("Role", lambda u: "Superadmin" if u["is_superuser"] else (u["role"] or "").capitalize()),
    "branch_name": ("Branch", lambda u: u["branch_name"] or "—"),
    "status": ("Status", lambda u: "Active" if u["is_active"] else "Inactive"),
    "created_at": ("Created At", lambda u: _fmt_dt(u["created_at"])),
    "updated_at": ("Updated At", lambda u: _fmt_dt(u["updated_at"])),
}

DEFAULT_COLUMNS = ["full_name", "email", "tenant_name", "role", "status", "created_at"]


def _fmt_dt(value: str | None) -> str:
    """Row values arrive as ISO strings (see admin/routes.py's row dict) —
    rendered human-readable here rather than carrying datetime objects
    through the export pipeline."""
    if not value:
        return ""
    try:
        return datetime.fromisoformat(value).strftime("%d %b %Y, %H:%M")
    except ValueError:
        return value


def resolve_columns(requested: list[str] | None) -> list[str]:
    if not requested:
        return DEFAULT_COLUMNS
    return [c for c in requested if c in COLUMN_DEFS] or DEFAULT_COLUMNS


def _filters_summary(filters: dict[str, Any]) -> list[tuple[str, str]]:
    labels = {
        "search": "Search", "tenant_name": "Business", "role": "Role",
        "status": "Status", "created_from": "Created From", "created_to": "Created To",
    }
    return [(labels[k], str(v)) for k, v in filters.items() if v not in (None, "")]


def _build_csv(rows: list[dict], columns: list[str]) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([COLUMN_DEFS[c][0] for c in columns])
    for row in rows:
        w.writerow([COLUMN_DEFS[c][1](row) for c in columns])
    # utf-8-sig so Excel (and other spreadsheet tools) detect UTF-8 correctly
    # instead of mis-decoding accented names — same convention used by every
    # other CSV export in this codebase.
    return buf.getvalue().encode("utf-8-sig")


def _build_xlsx(
    rows: list[dict], columns: list[str], generated_by: str, total: int, filters: dict[str, Any],
) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Users"

    title_font = Font(bold=True, size=16, color="16A34A")
    subtitle_font = Font(bold=True, size=12)
    meta_font = Font(size=10, color="6B7280")
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="16A34A", end_color="16A34A", fill_type="solid")

    r = 1
    ws.cell(r, 1, "PESAA").font = title_font
    r += 1
    ws.cell(r, 1, "Platform Users Report").font = subtitle_font
    r += 1
    ws.cell(r, 1, f"Generated: {datetime.now(UTC).strftime('%d %b %Y, %H:%M')} UTC").font = meta_font
    r += 1
    ws.cell(r, 1, f"Generated By: {generated_by}").font = meta_font
    r += 1
    ws.cell(r, 1, f"Total Users: {total}").font = meta_font
    r += 1

    applied = _filters_summary(filters)
    if applied:
        r += 1
        ws.cell(r, 1, "Applied Filters:").font = Font(bold=True, size=10)
        r += 1
        for label, value in applied:
            ws.cell(r, 1, f"{label}: {value}").font = meta_font
            r += 1

    r += 1  # blank row before the table
    header_row = r
    for col_idx, key in enumerate(columns, start=1):
        cell = ws.cell(header_row, col_idx, COLUMN_DEFS[key][0])
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="left", vertical="center")

    for row_offset, row in enumerate(rows, start=1):
        for col_idx, key in enumerate(columns, start=1):
            ws.cell(header_row + row_offset, col_idx, COLUMN_DEFS[key][1](row))

    last_row = header_row + len(rows)
    last_col_letter = get_column_letter(len(columns))
    ws.freeze_panes = f"A{header_row + 1}"
    if rows:
        ws.auto_filter.ref = f"A{header_row}:{last_col_letter}{last_row}"

    for col_idx, key in enumerate(columns, start=1):
        label = COLUMN_DEFS[key][0]
        widest = max([len(label)] + [len(COLUMN_DEFS[key][1](row)) for row in rows], default=len(label))
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max(widest + 2, 12), 40)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def build_users_export(
    rows: list[dict], columns: list[str], fmt: str, generated_by: str, filters: dict[str, Any],
) -> tuple[str, bytes, str]:
    """Turns already-fetched, already-filtered user rows into a downloadable
    file. Never touches the database — the caller (admin/routes.py) owns the
    single shared filtered query that both the dashboard and this export are
    built from, so the two can never drift apart."""
    day = datetime.now(UTC).strftime("%Y-%m-%d")
    is_filtered = any(v not in (None, "") for v in filters.values())
    base_name = f"pesaa_users_filtered_{day}" if is_filtered else f"pesaa_users_{day}"

    if fmt == "csv":
        return f"{base_name}.csv", _build_csv(rows, columns), "text/csv; charset=utf-8"

    content = _build_xlsx(rows, columns, generated_by, len(rows), filters)
    return f"{base_name}.xlsx", content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
